# Generated by Django 4.1.4 on 2022-12-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydebtors', '0004_rename_contact_contactdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name_plural': 'Contact Details'},
        ),
    ]
